"""Add exercise_name to record table

Revision ID: cef8c53c748b
Revises: ea792ad5392c
Create Date: 2025-03-28 13:44:18.989509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef8c53c748b'
down_revision = 'ea792ad5392c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_name', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'exercise', ['exercise_id'], ['id'])
        batch_op.drop_column('exercise_name')

    # ### end Alembic commands ###
